### ISSUE TITLE
Opening VFX files breaks the demos

### ISSUE THREAD

**Issue by brnkhy** [Unity-Technologies/VisualEffectGraph-Samples#1]
Hello,
I just downloaded Samples 4.9 Preview rev1 and having a little problems.
Samples run fine initially but as soon as I open VFX files in the vfx editor, they are permanently broken. I guess editor overrides some parameters or something on window initialization or something?

In example, voxel terrain demo looks like this after loading graph;
![unity_2019-02-07_17-20-49](https://user-images.githubusercontent.com/1465390/52417345-bba83900-2afc-11e9-8444-01f798bbcd72.png)

Genie
![unity_2019-02-07_17-22-08](https://user-images.githubusercontent.com/1465390/52417437-f316e580-2afc-11e9-8349-25953cd6d67d.jpg)

Radar;
![unity_2019-02-07_17-25-04](https://user-images.githubusercontent.com/1465390/52417617-5739a980-2afd-11e9-8374-13e58e4326a4.png)

I'm using 2018.3.3f1
Visual Effect Graph 4.9.0

**Comment by brnkhy** [comment]
I think this is happening because of encoding (Turkish local by the way)
as soon as I open a vfx file on editor, bunch of changes like below happens and of course breaks the vfx;
![tortoisegitmerge_2019-02-07_19-22-02](https://user-images.githubusercontent.com/1465390/52425742-a982c680-2b0d-11e9-82d7-21fe209f68a7.png)
capital i and I are different chars in Turkish so I suspect that's the problem.
Little strange though
`PARTICLEID` becomes `PART\u0130CLEID`
so first `I` changes to `\u0130` but not the second one.

Edit; `PARTICLEID` was just one example, there's a bunch of those like `POSITION` in there.

**Comment by peeweek** [comment]
Yes indeed, actually more a general unity3d / vfx graph issue that should be reported using the bug reporter (Menu Help/Report a bug).

This is an issue we already addressed and as you said, due to some locale encoding (turkish among others). It should be fixed in the future.

I will keep this issue open and once we have a fix push an update of this project so you can confirm it fixed.

**Comment by brnkhy** [comment]
thanks a lot for the response @peeweek!
I'm really looking forward to play with new samples.
