### ISSUE TITLE
Files is corrupted

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [Unity-Technologies/VisualEffectGraph-Samples#16]
I just finished downloading the project but the files is corrupted. Or is it just me?

**Comment by andybak** [comment]
Not sure what you mean by "corrupted". What errors are you seeing.

Also - it worked fine for me the day before yesterday. Master branch on Unity 2018.3.latest

**Comment by AliAkbarMontazeri** [comment]
I simply can't extract the .zip file. But it's working now. I think it's because I have an internet issue.
