### ISSUE TITLE
Moving to URP (LWRP)

### ISSUE THREAD

**Issue by paulosalvatore** [Unity-Technologies/VisualEffectGraph-Samples#17]
Is there any chance to switch the SRP to URP instead of HDRP?

Or any clues on moving some particles to URP?

**Comment by sterlingcrispin** [comment]
+1 URP request

**Comment by peeweek** [comment]
Hi, URP Parity is currently being wrapped up as part of 2021.2, and it makes a conversion of the samples something that _could_ happen in the future. 

https://portal.productboard.com/unity/1-unity-platform-rendering-visual-effects/tabs/9-visual-effect-graph


Moreover, this project could help us verify how to  make the HDRP > URP transition possible and with minimum user interaction. Not much sadly at the moment, regarding that transition.
