### ISSUE TITLE
vfx parameters from script

### ISSUE THREAD

**Issue by tanakataiki** [Unity-Technologies/VisualEffectGraph-Samples#2]
Does anybody tell me  how to set vfx block parameters from script?
It's shown in inspector yet I dont know how to get componet and parameters that I can set.

![vfxInspector](https://user-images.githubusercontent.com/37890520/54617899-738a1800-4aa5-11e9-94b7-8f2688fb9e45.PNG)

**Comment by kristafervale** [comment]
Someone correct me if I'm wrong, but I believe you can just do:

`visualEffect.SetFloat("parameter", 0);`

where parameter is the name of the parameter you want to set as a string.

**Comment by cocapasteque** [comment]
Bump on this, can't find a way to control my spawn rate via a script...
the SetFloat method from `UnityEngine.Experimental.VFX.VisualEffect` is not working, I have `Value type for 'SpawnRate' is incorrect` but it's the exact same name for the paramater.

EDIT : Nevermind, I forgot my parameter was Int and not float...
