### ISSUE TITLE
corrupted ZIP file

### ISSUE THREAD

**Issue by Pitamor** [Unity-Technologies/VisualEffectGraph-Samples#20]
Hi, 
I'm having troubles open the project zip file. 
If there is a chance to maybe upload it again it will be super helpful!
Thanks,

Itamar

**Comment by doukasd** [comment]
The GitHib Zip functionality does not include files that are tracked on Git LFS. Did you try to clone the repo and did that not work for you?

**Comment by ShafinSikder** [comment]
use Github cli
