### ISSUE TITLE
Why Line output contains multiple "Set Position"?

### ISSUE THREAD

**Issue by ice-github** [Unity-Technologies/VisualEffectGraph-Samples#4]
I checked ARRadar sample however I couldn't understand why Line output of "Radar Lines" contains two "Set Position".
![image](https://user-images.githubusercontent.com/7911700/57570537-26d81300-743e-11e9-83a3-acbd9d8a2125.png)
I'd like to know how VFXGraph processes such a multiple "Set Position".
Second "Set Position" loads "Get Attribute position(Current)" and the *current* position means the value of the first "Set Position"?

**Comment by peeweek** [comment]
In this output every line particle is actually a wireframe segment (2 points) controlled by attributes: 
- position for one end
- targetPosition for the other end

The first set position/target position are computing the values in 2d to make the grid), then are remapped as a vortex in separate set position/targetposition (basically these read the from values from the values stored previously using Get Position / Get Target Position operators.

This is something that is allowed in VFX, where you can perform some computations early in a context, then re-read again later in the same function.

As the blocks are executed top to bottom, you can chain computations this way.
