### ISSUE TITLE
No nodes in MorphingFace

### ISSUE THREAD

**Issue by githubcatw** [Unity-Technologies/VisualEffectGraph-Samples#6]
The MorphingFace example only shows the parameters and the attach panel. It should have more nodes that do the FX.
![image](https://user-images.githubusercontent.com/17374742/64476582-3cb5d480-d1a1-11e9-805a-459decb4b28c.png)
_(I played around with the parameters thinking they would change the simulation but there is no effect.)_

**Comment by andybak** [comment]
Working for me. Which Unity versions and which VFX Graph and HDRP versions are you using?

(and just checking - you've grabbing the latest git HEAD from the master branch of this repo?)

**Comment by githubcatw** [comment]
nevermind, I scrolled around and found it.
