### ISSUE TITLE
UnityEngine.Experimental Not linking to .VFX Library

### ISSUE THREAD

**Issue by michaeljsamuels** [Unity-Technologies/VisualEffectGraph-Samples#8]
Apologies if this isn't the right repo to be asking this, but I've been unable to find the core VFX git repo after a few hours of searching...

I am unable to get scripting working for my VFX graphs in Visual Studio. I am able to create VFX graphs using the editor, and create exposed parameters (i.e. the VFX packages is definitely imported in Unity), but when I try to include:

UnityEngine.Experimental.VFX

Visual Studio can't seem to find the module. Is there an additional step I need to take to include the module?

Thank You

**Comment by ufcyg** [comment]
remove the ".Experimental", atleast for 2019.3.8f1
