### ISSUE TITLE
New Version is not working

### ISSUE THREAD

**Issue by lijualivenow** [Unity-Technologies/VisualEffectGraph-Samples#9]
I am using Windows 10, unity 2019.2.7f  and 2019.2.0f, new project sample is not working. It crashes after a while package resolving.

**Comment by sourya-sen** [comment]
Unity 2019.3 has multiple errors and doesn't work, either.

**Comment by bryanrtboy** [comment]
`Library/PackageCache/com.unity.cinemachine@2.3.4/Runtime/PostProcessing/CinemachineVolumeSettings.cs(5,42): error CS0234: The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)`

Changing UnityEngine.Experimental.Rendering to UnityEngine.Rendering breaks other things, as does updating Cinemachine to latest preview. In short, it is not possible to run these examples in 2019.3.f1.

**Comment by muqian3288** [comment]
The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)
Unity2019.3.6f1

**Comment by muqian3288** [comment]
> `Library/PackageCache/com.unity.cinemachine@2.3.4/Runtime/PostProcessing/CinemachineVolumeSettings.cs(5,42): error CS0234: The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)`
> 
> Changing UnityEngine.Experimental.Rendering to UnityEngine.Rendering breaks other things, as does updating Cinemachine to latest preview. In short, it is not possible to run these examples in 2019.3.f1.

**Comment by muqian3288** [comment]
> `Library/PackageCache/com.unity.cinemachine@2.3.4/Runtime/PostProcessing/CinemachineVolumeSettings.cs(5,42): error CS0234: The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)`
> 
> Changing UnityEngine.Experimental.Rendering to UnityEngine.Rendering breaks other things, as does updating Cinemachine to latest preview. In short, it is not possible to run these examples in 2019.3.f1.

The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)
Unity2019.3.6f1

**Comment by davidboon78** [comment]
Also experiencing this problem: 
using UnityEngine.Experimental.Rendering.HDPipeline; 
causes:
The type or namespace name 'HDPipeline' does not exist in the namespace 'UnityEngine.Experimental.Rendering' (are you missing an assembly reference?)	
Unity 2019.3.12f1

**Comment by Prashant29** [comment]
I'm also experiencing this problem, Any update on this?

Thanks in advance!

**Comment by alikrc** [comment]
just update on ur own, it works.
